name: RetroArch Windows Nightly Build

on:
  schedule:
  - cron: "0 5 * * *"
  watch:
    types: [started]
    if: github.actor == github.event.repository.owner.login

jobs:
  job1:
    name: Build RetroArch Nightly Windows
    runs-on: windows-latest

    steps:
    - uses: numworks/setup-msys2@v1
      with:
        msystem: MINGW64
    - run: msys2do pacman -S --noconfirm --disable-download-timeout --needed wget git make mingw-w64-x86_64-toolchain mingw-w64-x86_64-ntldd mingw-w64-x86_64-zlib mingw-w64-x86_64-pkg-config mingw-w64-x86_64-SDL2 mingw-w64-x86_64-libxml2 mingw-w64-x86_64-freetype mingw-w64-x86_64-python3 mingw-w64-x86_64-ffmpeg mingw-w64-x86_64-drmingw mingw-w64-x86_64-qt5 mingw-w64-x86_64-openssl unzip p7zip
    - uses: actions/checkout@v2
    - name: Fetch the source
      run: msys2do git clone https://github.com/libretro/RetroArch.git
    - name: Configure
      working-directory: RetroArch
      run: msys2do ./configure --enable-qt
    - name: Build
      working-directory: RetroArch
      run: msys2do make -j8
    - name: Setup working dir
      run: mkdir working_dir
    - name: Make asset dirs
      working-directory: working_dir
      run: |
        msys2do mkdir assets
        msys2do mkdir shaders
        msys2do mkdir database
        msys2do mkdir cheats
        msys2do mkdir info
    - name: Qt deploy
      working-directory: RetroArch
      run: msys2do windeployqt --release --no-patchqt --no-translations retroarch.exe
    - name: Gather Qt libs
      working-directory: RetroArch
      run: ForEach ($l in $(msys2do ntldd.exe -R 'imageformats/*dll' | grep mingw64 | sed -e 's/^[ \t]*//'|cut -d' ' -f3)){cp "$l" ../working_dir}
    - name: Gather the other libs
      working-directory: RetroArch
      run: ForEach ($l in $(msys2do ntldd.exe -R '*.exe'|grep mingw64|sed -e 's/^[ \t]*//'|cut -d' ' -f3)){cp "$l" ../working_dir}
    - name: Free up some disk space
      working-directory: RetroArch
      run: msys2do rm -rf .git && msys2do pacman -Rsu --noconfirm mingw-w64-x86_64-toolchain mingw-w64-x86_64-qt5 mingw-w64-x86_64-openssl
    - name: Create debug exe and strip regular exe
      working-directory: RetroArch
      run: msys2do cp retroarch.exe retroarch_debug.exe && msys2do strip -s retroarch.exe
    - name: Fetch assets
      working-directory: working_dir/assets
      run: msys2do wget https://buildbot.libretro.com/assets/frontend/assets.zip && msys2do unzip assets.zip && msys2do rm assets.zip
    - name: Fetch overlays
      working-directory: working_dir
      run: msys2do git clone https://github.com/libretro/common-overlays.git && msys2do mv common-overlays overlays
    - name: Fetch autoconfigs
      working-directory: working_dir
      run: msys2do git clone https://github.com/libretro/retroarch-joypad-autoconfig.git && msys2do mv retroarch-joypad-autoconfig autoconfig
    - name: Fetch shaders
      working-directory: working_dir/shaders
      run: |
        msys2do git clone https://github.com/libretro/glsl-shaders.git && msys2do mv glsl-shaders shaders_glsl
        msys2do git clone https://github.com/libretro/slang-shaders.git && msys2do mv slang-shaders shaders_slang
        msys2do git clone https://github.com/libretro/common-shaders.git && msys2do mv common-shaders shaders_cg
    - name: Fetch databases
      working-directory: working_dir/database
      run: msys2do wget https://buildbot.libretro.com/assets/frontend/database-rdb.zip && msys2do unzip database-rdb.zip && msys2do rm database-rdb.zip
    - name: Fetch cheats
      working-directory: working_dir/cheats
      run: msys2do wget https://buildbot.libretro.com/assets/frontend/cheats.zip && msys2do unzip cheats.zip && msys2do rm cheats.zip
    - name: Fetch core info
      working-directory: working_dir/info
      run: msys2do wget https://buildbot.libretro.com/assets/frontend/info.zip && msys2do unzip info.zip && msys2do rm info.zip
    - name: Move executables to working dir (libs are already there)
      working-directory: RetroArch
      run: mv *.exe ../working_dir
    - name: Zip the full release
      working-directory: working_dir
      run: 7z a -mx=9 RetroArch-Win-x86_64-Nightly_Full.7z *
    - name: Zip just the executables and libs
      working-directory: working_dir
      run: 7z a -mx=9 RetroArch-Update-Pack-Win-x86_64-Nightly.7z *.exe *dll
    - name: Upload RetroArch release bundle
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: working_dir/RetroArch-Win-x86_64-Nightly_Full.7z
        tag: Nightlies
        asset_name: RetroArch-Win-x86_64-Nightly_Full.7z
        overwrite: true
    - name: Upload Update Pack
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: working_dir/RetroArch-Update-Pack-Win-x86_64-Nightly.7z
        tag: Nightlies
        asset_name: RetroArch-Update-Pack-Win-x86_64-Nightly.7z
        overwrite: true
